WEB_TRUONG_SP/Models/SubMenu.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Web.UI.WebControls;
using System;

namespace WEB_TRUONG_SP.Models
{
    public class SubMenu 
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [Required(ErrorMessage = "Tên không được để trống")]
        public string Name { get; set; }

        public DateTime CreateDate { get; set; }

        public int MenuID { get; set; }

        public bool IsDelete { get; set; }

        [ForeignKey("MenuID")]
        public virtual MenuModel Menu { get; set; }
        public SubMenu()
        {
            CreateDate = DateTime.Now;
            IsDelete = false;
        }
    }
}

WEB_TRUONG_SP/Areas/Admin/Controllers/SubMenuController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WEB_TRUONG_SP.Models;

namespace WEB_TRUONG_SP.Areas.Admin.Controllers
{
    [RouteArea("Admin")]
    public class SubMenuController : Controller
    {
        ApplicationDBContext db = new ApplicationDBContext();
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            var subMenus = db.SubMenu.Where(x => !x.IsDelete).
                OrderByDescending(x => x.CreateDate).ToList();
            ViewBag.Menu = db.Menus.Where(x => !x.IsDelete).ToList();
            int pageSize = 6;
            return View(subMenus.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult Add()
        {
            var menus = db.Menus.Where(x => !x.IsDelete).Select(x => new
            {
                x.ID,
                x.Name
            }).ToList();

            ViewBag.MenuID = new SelectList(menus, "ID", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(SubMenu menu)
        {
            if (ModelState.IsValid)
            {
                db.SubMenu.Add(menu);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            var menus = db.Menus.Where(x => !x.IsDelete).Select(x => new
            {
                x.ID,
                x.Name
            }).ToList();

            ViewBag.MenuID = new SelectList(menus, "ID", "Name");
            return View(menu);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var menus = db.Menus.Where(x => !x.IsDelete).Select(x => new
            {
                x.ID,
                x.Name
            }).ToList();

            ViewBag.MenuID = new SelectList(menus, "ID", "Name");

            var menuEdit = db.SubMenu.Where(x => x.ID == id).FirstOrDefault();
            if (menuEdit == null) return HttpNotFound();
            return View(menuEdit);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SubMenu submenu)
        {
            if (ModelState.IsValid)
            {
                submenu.CreateDate = DateTime.Now;
                db.Entry(submenu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var menus = db.Menus.Where(x => !x.IsDelete).Select(x => new
            {
                x.ID,
                x.Name
            }).ToList();

            ViewBag.MenuID = new SelectList(menus, "ID", "Name", submenu.MenuID);
            return View(submenu);
        }

        public ActionResult Remove(int id)
        {
            var menuRemove = db.SubMenu.Where(x => x.ID == id).FirstOrDefault();
            if (menuRemove == null) return HttpNotFound();
            if (ModelState.IsValid)
            {
                menuRemove.IsDelete = true;
                db.Entry(menuRemove).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(menuRemove);
        }

        public ActionResult RestoreIndex()
        {
            var menus = db.SubMenu.Where(x => x.IsDelete).ToList();
            ViewBag.Menu = db.Menus.Where(x => !x.IsDelete).ToList();
            return View(menus);
        }
        public ActionResult Restore(int id)
        {
            var menu = db.SubMenu.Where(x => x.ID == id).FirstOrDefault();
            if (menu == null) return HttpNotFound();

            menu.IsDelete = false;
            db.Entry(menu).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("RestoreIndex");
        }
        [HttpGet]
        public ActionResult Search(string searchString)
        {
            if (string.IsNullOrEmpty(searchString)) return HttpNotFound();
            var menu = db.SubMenu
             .Where(x => x.Name.ToLower().Contains(searchString.ToLower()) && !x.IsDelete)
             .ToList();
            if (menu == null || menu.Count == 0) return HttpNotFound();
            ViewBag.Menu = db.Menus.Where(x => !x.IsDelete).ToList();
            return View(menu);
        }
    }
}

WEB_TRUONG_SP/Areas/Admin/Views/SubMenu/Add.cshtml
@model WEB_TRUONG_SP.Models.SubMenu

@{
    ViewBag.Title = "Thêm Menu Con";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}

<h2>Thêm Menu Con</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MenuID, "Menu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MenuID, ViewBag.MenuID as SelectList, "Select a Menu", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MenuID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div class="btn btn-primary" style="">
    @Html.ActionLink("Trở về", "Index", null, new { @class = "text-white" })
</div>

WEB_TRUONG_SP/Areas/Admin/Views/SubMenu/Edit.cshtml
@model WEB_TRUONG_SP.Models.SubMenu

@{
    ViewBag.Title = "Edit Menu Con";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}

<h2>Edit Menu Con</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MenuID, "Menu", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.MenuID, ViewBag.MenuID as SelectList, "Select a Menu", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MenuID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div class="btn btn-primary" style="">
    @Html.ActionLink("Trở về", "Index", null, new { @class = "text-white" })
</div>

WEB_TRUONG_SP/Areas/Admin/Views/SubMenu/Index.cshtml
@model PagedList.IPagedList<WEB_TRUONG_SP.Models.SubMenu>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Menu Con";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}
<style>
    .table-striped tbody tr:nth-of-type(odd) {
        background-color: #f9f9f9;
    }

    .table-striped tbody tr:nth-of-type(even) {
        background-color: #e9ecef;
    }
</style>
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
          action="@Url.Action("Search", "SubMenu", new {area ="Admin"})" method="get">
        <div class="input-group">
            <input type="text" name="searchString" class="form-control bg-light border-0 small"
                   placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                    <i class="fa fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                 aria-labelledby="searchDropdown">
                <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
                      action="@Url.Action("Search", "SubMenu", new {area = "Admin"})" method="get">
                    <div class="input-group">
                        <input type="text" name="searchString" class="form-control bg-light border-0 small"
                               placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fa fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>
    </ul>
</nav>
<!-- End of Topbar -->
<h2>Quản lý Menu Con</h2>
<div class="container mt-5">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Tên Menu</th>
                <th scope="col">Menu cha</th>
                <th scope="col">Ngày Tạo</th>
                <th scope="col">Xóa</th>
                <th scope="col">Sửa</th>
            </tr>
        </thead>
        <tbody>
            @if (Model == null) { return; }
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@item.ID</th>
                    <td>@item.Name</td>
                    <td>
                        @foreach (var menu in ViewBag.Menu)
                        {
                            if (menu.ID == item.ID)
                            {
                                @menu.Name
                            }
                        }
                    </td>
                    <td>@item.CreateDate</td>
                    <td>
                        <a href="@Url.Action("Remove", "SubMenu", new { area = "Admin", id = item.ID })" class="btn btn-danger"
                           onclick="return confirmDelete('@item.ID')">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                    <td>
                        <a href="@Url.Action("Edit","SubMenu",
                                new { area = "Admin", id = item.ID })" class="btn btn-warning">
                            <i class="fa fa-edit"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div style="display:flex; gap:10px">
        <a href="@Url.Action("Add","SubMenu",
                                new { area = "Admin"})" class="btn btn-success">
            <i class="fa fa-plus"></i>
        </a>
        <a href="@Url.Action("RestoreIndex","SubMenu",
                                new { area = "Admin"})" class="btn btn-primary">
            <i class="fa fa-refresh"></i>
        </a>
    </div>
</div>

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }), new PagedListRenderOptions
{
    LiElementClasses = new string[] { "page-item" },
    UlElementClasses = new[] { "pagination" },
})


<script type="text/javascript">
    function confirmDelete(itemId) {
        if (confirm("Bạn có chắc muốn xóa menu này?")) {
            window.location.href = '@Url.Action("Remove", "SubMenu", new { area = "Admin" })' + '/' + itemId;
        }
        return false;
    }
</script>

WEB_TRUONG_SP/Areas/Admin/Views/SubMenu/RestoreIndex.cshtml
@{
    ViewBag.Title = "Khôi Phục";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}

<h2>Khôi phục Menu Con</h2>
<div class="container mt-5">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Tên Menu</th>
                <th scope="col">Tên Menu Cha</th>
                <th scope="col">Ngày Tạo</th>
                <th scope="col">Khôi phục</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@item.ID</th>
                    <td>@item.Name</td>
                    <td>
                        @foreach (var menu in ViewBag.Menu)
                        {
                            if (menu.ID == item.ID)
                            {
                                @menu.Name
                            }
                        }
                    </td>
                    <td>@item.CreateDate</td>
                    <td>
                        <a href="@Url.Action("Restore", "SubMenu", new { area = "Admin", id = item.ID })" class="btn btn-warning"
                           onclick="return confirmDelete('@item.ID')">
                            <i class="fa fa-recycle"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="btn btn-primary" style="">
    @Html.ActionLink("Trở về", "Index", null, new { @class = "text-white" })
</div>
<script type="text/javascript">
    function confirmDelete(itemId) {
        if (confirm("Bạn có chắc muốn khôi phục menu này?")) {
            window.location.href = '@Url.Action("Restore", "SubMenu", new { area = "Admin" })' + '/' + itemId;
        }
        return false;
    }
</script>

WEB_TRUONG_SP/Areas/Admin/Views/SubMenu/Search.cshtml
@{
    ViewBag.Title = "Tìm kiếm";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}
<style>
    .table-striped tbody tr:nth-of-type(odd) {
        background-color: #f9f9f9;
    }

    .table-striped tbody tr:nth-of-type(even) {
        background-color: #e9ecef;
    }
</style>
<h2>Kết quả tìm kiếm</h2>
<div class="container mt-5">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Tên Menu</th>
                <th scope="col">Tên Menu Con</th>
                <th scope="col">Ngày Tạo</th>
                <th scope="col">Xóa</th>
                <th scope="col">Sửa</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@item.ID</th>
                    <td>@item.Name</td>
                    <td>
                        @foreach (var menu in ViewBag.Menu)
                        {
                            if (menu.ID == item.ID)
                            {
                                @menu.Name
                            }
                        }
                    </td>
                    <td>@item.CreateDate</td>
                    <td>
                        <a href="@Url.Action("Remove", "SubMenu", new { area = "Admin", id = item.ID })" class="btn btn-danger"
                           onclick="return confirmDelete('@item.ID')">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                    <td>
                        <a href="@Url.Action("Edit","SubMenu",
                                new { area = "Admin", id = item.ID })" class="btn btn-warning">
                            <i class="fa fa-edit"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="btn btn-primary" style="">
        @Html.ActionLink("Trở về", "Index", null, new { @class = "text-white" })
    </div>
</div>

<script type="text/javascript">
    function confirmDelete(itemId) {
        if (confirm("Bạn có chắc muốn xóa menu con này không?")) {
            window.location.href = '@Url.Action("Remove", "SubMenu", new { area = "Admin" })' + '/' + itemId;
        }
        return false;
    }
</script>