WEB_TRUONG_SP/Models/Lecturer.cs
using System.ComponentModel.DataAnnotations;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace WEB_TRUONG_SP.Models
{
    public class Lecturer
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [Required(ErrorMessage = "Tên không được để trống")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Chức vụ không được để trống")]
        public string Position { get; set; }

        [Required(ErrorMessage = "Bằng cấp không được để trống")]
        public string Degree { get; set; }

        public string Information { get; set; }

        public string ImagePath { get; set; }

        public DateTime CreateDate { get; set; }

        public string Field { get; set; }

        [Required(ErrorMessage = "Chức vụ hội đồng không được để trống nếu không có thì để không")]
        public string CouncilPosition { get; set; }

        public bool IsDelete { get; set; }

        public Lecturer()
        {
            CreateDate = DateTime.Now;
            IsDelete = false;
        }
    }
}

WEB_TRUONG_SP/Areas/Admin/Controllers/LecturerController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using WEB_TRUONG_SP.Models;

namespace WEB_TRUONG_SP.Areas.Admin.Controllers
{
    [RouteArea("Admin")]
    public class LecturerController : Controller
    {
        ApplicationDBContext db = new ApplicationDBContext();
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            var menus = db.Lecturer.Where(x => !x.IsDelete).OrderByDescending(x => x.CreateDate).ToList();
            int pageSize = 6;
            return View(menus.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(Lecturer lecturer, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                var file = Request.Files["ImageFile"];
                if (file != null && file.ContentLength > 0)
                {
                    lecturer.ImagePath = LoadImgName(ImageFile);
                    db.Lecturer.Add(lecturer);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("ImageFile", "Ảnh không được để trống");
                    return View(lecturer);
                }
            }
            return View(lecturer);
        }
        public string LoadImgName(HttpPostedFileBase ImageFile)
        {
            string path = "";
            if (ImageFile != null && ImageFile.ContentLength > 0)
            {
                var uploadDir = "~/ImgPath/Lecturer";
                var imagePath = Path.Combine(Server.MapPath(uploadDir), Path.GetFileName(ImageFile.FileName));
                path = Path.Combine(uploadDir, Path.GetFileName(ImageFile.FileName));
                ImageFile.SaveAs(imagePath);
            }
            return path;
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var lecEdit = db.Lecturer.Where(x => x.ID == id).FirstOrDefault();
            if (lecEdit == null) return HttpNotFound();
            return View(lecEdit);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Lecturer lecturer, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                var oldPathImg = lecturer.ImagePath;

                if (ImageFile != null && ImageFile.ContentLength > 0)
                {
                    lecturer.ImagePath = CheckDeleteOrUpdateImg(oldPathImg, ImageFile);
                }
                else
                {
                    lecturer.ImagePath = oldPathImg;
                }
                lecturer.CreateDate = DateTime.Now;
                db.Entry(lecturer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(lecturer);
        }

        public string CheckDeleteOrUpdateImg(string oldPathImg, HttpPostedFileBase ImageFile)
        {
            string uploadDir = "~/ImgPath/Lecturer";
            string fileName = Path.GetFileName(ImageFile.FileName);
            string newPathImg = Path.Combine(uploadDir, fileName);
            string imagePathNew = Server.MapPath(newPathImg);

            if (!string.IsNullOrEmpty(oldPathImg))
            {
                string pathOldImg = Path.Combine(Server.MapPath(uploadDir), Path.GetFileName(oldPathImg));

                if (System.IO.File.Exists(pathOldImg) && !pathOldImg.Equals(imagePathNew, StringComparison.OrdinalIgnoreCase))
                {
                    System.IO.File.Delete(pathOldImg);
                }
            }

            ImageFile.SaveAs(imagePathNew);

            return newPathImg;
        }

        public ActionResult Remove(int id)
        {
            var lecRemove = db.Lecturer.Where(x => x.ID == id).FirstOrDefault();
            if (lecRemove == null) return HttpNotFound();
            if (ModelState.IsValid)
            {
                lecRemove.IsDelete = true;
                db.Entry(lecRemove).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lecRemove);
        }

        public ActionResult RestoreIndex()
        {
            var lecturers = db.Lecturer.Where(x => x.IsDelete).ToList();
            return View(lecturers);
        }
        public ActionResult Restore(int id)
        {
            var lecturer = db.Lecturer.Where(x => x.ID == id).FirstOrDefault();
            if (lecturer == null) return HttpNotFound();

            lecturer.IsDelete = false;
            db.Entry(lecturer).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("RestoreIndex");
        }
        [HttpGet]
        public ActionResult Search(string searchString)
        {
            if (string.IsNullOrEmpty(searchString)) return HttpNotFound();
            var lecturers = db.Lecturer
             .Where(x => x.Name.ToLower().Contains(searchString.ToLower()) && !x.IsDelete)
             .ToList();
            if (lecturers == null || lecturers.Count == 0) return HttpNotFound();
            return View(lecturers);
        }
    }
}

WEB_TRUONG_SP/Areas/Admin/Controllers/MenuController.cs
using PagedList;
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using WEB_TRUONG_SP.Models;

namespace WEB_TRUONG_SP.Areas.Admin.Controllers
{
    [RouteArea("Admin")]
    public class MenuController : Controller
    {
        ApplicationDBContext db = new ApplicationDBContext();
        public ActionResult Index(int? page )
        {
            int pageNumber = (page ?? 1);
            var menus = db.Menus.Where(x => !x.IsDelete).OrderByDescending(x=>x.CreateDate).ToList();
            int pageSize = 6;
            return View(menus.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(MenuModel menu)
        {
            if (ModelState.IsValid)
            {
                db.Menus.Add(menu);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(menu);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var menuEdit = db.Menus.Where(x => x.ID == id).FirstOrDefault();
            if (menuEdit == null) return HttpNotFound();
            return View(menuEdit);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MenuModel menu)
        {
            if (ModelState.IsValid)
            {
                menu.CreateDate = DateTime.Now;
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(menu);
        }

        public ActionResult Remove(int id)
        {
            var menuRemove = db.Menus.Where(x => x.ID == id).FirstOrDefault();
            if (menuRemove == null) return HttpNotFound();
            if (ModelState.IsValid)
            {
                menuRemove.IsDelete = true;
                db.Entry(menuRemove).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(menuRemove);
        }

        public ActionResult RestoreIndex()
        {
            var menus = db.Menus.Where(x => x.IsDelete).ToList();
            return View(menus);
        }
        public ActionResult Restore(int id)
        {
            var menu = db.Menus.Where(x => x.ID == id).FirstOrDefault();
            if (menu == null) return HttpNotFound();

            menu.IsDelete = false;
            db.Entry(menu).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("RestoreIndex");
        }
        [HttpGet]
        public ActionResult Search(string searchString)
        {
            if (string.IsNullOrEmpty(searchString)) return HttpNotFound();
            var menu = db.Menus
             .Where(x => x.Name.ToLower().Contains(searchString.ToLower()) && !x.IsDelete)
             .ToList();
            if (menu == null || menu.Count == 0) return HttpNotFound();
            return View(menu);
        }
    }
}

WEB_TRUONG_SP/Areas/Admin/Views/Lecturer/Add.cshtml
@model WEB_TRUONG_SP.Models.Lecturer

@{
    ViewBag.Title = "Thêm giảng viên";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}

<h2>Thêm giảng viên</h2>

@using (Html.BeginForm("Add", "Lecturer", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Position, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Degree, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Degree, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Degree, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Information, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Information, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Information, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" class="form-control" />
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Field, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Field, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Field, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CouncilPosition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.CouncilPosition, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CouncilPosition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div class="btn btn-primary">
    @Html.ActionLink("Trở về", "Index", null, new { @class = "text-white" })
</div>

WEB_TRUONG_SP/Areas/Admin/Views/Lecturer/Edit.cshtml
@model WEB_TRUONG_SP.Models.Lecturer

@{
    ViewBag.Title = "Chỉnh sửa GV";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}

<h2>Chỉnh sửa GV</h2>

@using (Html.BeginForm("Edit", "Lecturer", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Position, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Degree, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Degree, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Degree, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Information, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Information, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Information, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (!string.IsNullOrEmpty(Model.ImagePath))
                {
                    <img src="@Url.Content(Model.ImagePath)" alt="Image" style="max-width: 100px; max-height: 100px;" />
                }
                <input type="file" name="ImageFile" class="form-control" value="@Model.ImagePath" />
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Field, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Field, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Field, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CouncilPosition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.CouncilPosition, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CouncilPosition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div class="btn btn-primary">
    @Html.ActionLink("Trở về", "Index", null, new { @class = "text-white" })
</div>

WEB_TRUONG_SP/Areas/Admin/Views/Lecturer/Index.cshtml
@model PagedList.IPagedList<WEB_TRUONG_SP.Models.Lecturer>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Giảng viên";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}
<style>
    .table-striped tbody tr:nth-of-type(odd) {
        background-color: #f9f9f9;
    }

    .table-striped tbody tr:nth-of-type(even) {
        background-color: #e9ecef;
    }
</style>
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
          action="@Url.Action("Search", "Lecturer", new {area ="Admin"})" method="get">
        <div class="input-group">
            <input type="text" name="searchString" class="form-control bg-light border-0 small"
                   placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                    <i class="fa fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                 aria-labelledby="searchDropdown">
                <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
                      action="@Url.Action("Search", "Menu", new {area = "Admin"})" method="get">
                    <div class="input-group">
                        <input type="text" name="searchString" class="form-control bg-light border-0 small"
                               placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fa fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>
    </ul>
</nav>
<!-- End of Topbar -->
<h2>Quản lý Menu</h2>
<div class="container mt-5">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Tên GV</th>
                <th scope="col">Chức vụ</th>
                <th scope="col">Bằng cấp</th>
                <th scope="col">Thông tin</th>
                <th scope="col">Lĩnh vực</th>
                <th scope="col">Hội đồng</th>
                <th scope="col">Xóa</th>
                <th scope="col">Sửa</th>
            </tr>
        </thead>
        <tbody>
            @if (Model == null) { return; }
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@item.ID</th>
                    <td>@item.Name</td>
                    <td>@item.Position</td>
                    <td>@item.Degree</td>
                    <td>@item.Information</td>
                    <td>@item.Field</td>
                    <td>@item.CouncilPosition</td>
                    <td>
                        <a href="@Url.Action("Remove", "Lecturer", new { area = "Admin", id = item.ID })" class="btn btn-danger"
                           onclick="return confirmDelete('@item.ID')">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                    <td>
                        <a href="@Url.Action("Edit","Lecturer",
                                new { area = "Admin", id = item.ID })" class="btn btn-warning">
                            <i class="fa fa-edit"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div style="display:flex; gap:10px">
        <a href="@Url.Action("Add","Lecturer",
                                new { area = "Admin"})" class="btn btn-success">
            <i class="fa fa-plus"></i>
        </a>
        <a href="@Url.Action("RestoreIndex","Lecturer",
                                new { area = "Admin"})" class="btn btn-primary">
            <i class="fa fa-refresh"></i>
        </a>
    </div>
</div>

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }), new PagedListRenderOptions
{
    LiElementClasses = new string[] { "page-item" },
    UlElementClasses = new[] { "pagination" },
})


<script type="text/javascript">
    function confirmDelete(itemId) {
        if (confirm("Bạn có chắc muốn xóa thành viên này không?")) {
            window.location.href = '@Url.Action("Remove", "Lecturer", new { area = "Admin" })' + '/' + itemId;
        }
        return false;
    }
</script>

WEB_TRUONG_SP/Areas/Admin/Views/Lecturer/RestoreIndex.cshtml
@{
    ViewBag.Title = "Khôi Phục";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}

<h2>Khôi phục GV</h2>
<div class="container mt-5">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Tên GV</th>
                <th scope="col">Chức vụ</th>
                <th scope="col">Bằng cấp</th>
                <th scope="col">Thông tin</th>
                <th scope="col">Lĩnh vực</th>
                <th scope="col">Hội đồng</th>
                <th scope="col">Khôi phục</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@item.ID</th>
                    <td>@item.Name</td>
                    <td>@item.Position</td>
                    <td>@item.Degree</td>
                    <td>@item.Information</td>
                    <td>@item.Field</td>
                    <td>@item.CouncilPosition</td>
                    <td>
                        <a href="@Url.Action("Restore", "Lecturer", new { area = "Admin", id = item.ID })" class="btn btn-warning"
                           onclick="return confirmDelete('@item.ID')">
                            <i class="fa fa-recycle"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="btn btn-primary" style="">
    @Html.ActionLink("Trở về", "Index", null, new { @class = "text-white" })
</div>
<script type="text/javascript">
    function confirmDelete(itemId) {
        if (confirm("Bạn có chắc muốn khôi phục GV này không?")) {
            window.location.href = '@Url.Action("Restore", "Lecturer", new { area = "Admin" })' + '/' + itemId;
        }
        return false;
    }
</script>

WEB_TRUONG_SP/Areas/Admin/Views/Lecturer/Search.cshtml
@{
    ViewBag.Title = "Tìm kiếm";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml";
}
<style>
    .table-striped tbody tr:nth-of-type(odd) {
        background-color: #f9f9f9;
    }

    .table-striped tbody tr:nth-of-type(even) {
        background-color: #e9ecef;
    }
</style>
<h2>Kết quả tìm kiếm</h2>
<div class="container mt-5">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Tên GV</th>
                <th scope="col">Chức vụ</th>
                <th scope="col">Bằng cấp</th>
                <th scope="col">Thông tin</th>
                <th scope="col">Lĩnh vực</th>
                <th scope="col">Hội đồng</th>
                <th scope="col">Xóa</th>
                <th scope="col">Sửa</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@item.ID</th>
                    <td>@item.Name</td>
                    <td>@item.Position</td>
                    <td>@item.Degree</td>
                    <td>@item.Information</td>
                    <td>@item.Field</td>
                    <td>@item.CouncilPosition</td>
                    <td>
                        <a href="@Url.Action("Remove", "Lecturer", new { area = "Admin", id = item.ID })" class="btn btn-danger"
                           onclick="return confirmDelete('@item.ID')">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                    <td>
                        <a href="@Url.Action("Edit","Lecturer",
                                new { area = "Admin", id = item.ID })" class="btn btn-warning">
                            <i class="fa fa-edit"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="btn btn-primary" style="">
        @Html.ActionLink("Trở về", "Index", null, new { @class = "text-white" })
    </div>
</div>

<script type="text/javascript">
    function confirmDelete(itemId) {
        if (confirm("Bạn có chắc muốn xóa GV này không?")) {
            window.location.href = '@Url.Action("Remove", "Lecturer", new { area = "Admin" })' + '/' + itemId;
        }
        return false;
    }
</script>