WEB_TRUONG_SP/Areas/Admin/Controllers/BannerController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WEB_TRUONG_SP.Models;

namespace WEB_TRUONG_SP.Areas.Admin.Controllers
{
    public class BannerController : Controller
    {
        ApplicationDBContext db = new ApplicationDBContext();
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            var department = db.Banner.Where(x => !x.IsDelete).OrderByDescending(x => x.CreateDate).ToList();
            int pageSize = 6;
            return View(department.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(Banner banner, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                var flie = Request.Files["ImageFile"];
                if(flie != null && flie.ContentLength > 0)
                {
                    banner.ImgPath = LoadImgName(ImageFile);
                    db.Banner.Add(banner);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return View(banner);
        }

        public string LoadImgName(HttpPostedFileBase ImageFile)
        {
            string path = "";
            if (ImageFile != null && ImageFile.ContentLength > 0)
            {
                var uploadDir = "~/ImgPath/Banner";
                var imagePath = Path.Combine(Server.MapPath(uploadDir), Path.GetFileName(ImageFile.FileName));
                path = Path.Combine(uploadDir, Path.GetFileName(ImageFile.FileName));
                ImageFile.SaveAs(imagePath);
            }
            return path;
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var banEdit = db.Banner.Where(x => x.ID == id).FirstOrDefault();
            if (banEdit == null) return HttpNotFound();
            return View(banEdit);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Banner banner, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                var oldPathImg = banner.ImgPath;

                if (ImageFile != null && ImageFile.ContentLength > 0)
                {
                    banner.ImgPath = CheckDeleteOrUpdateImg(oldPathImg, ImageFile);
                }
                else
                {
                    banner.ImgPath = oldPathImg;
                }
                banner.CreateDate = DateTime.Now;
                db.Entry(banner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(banner);
        }

        public string CheckDeleteOrUpdateImg(string oldPathImg, HttpPostedFileBase ImageFile)
        {
            string uploadDir = "~/ImgPath/Banner";
            string fileName = Path.GetFileName(ImageFile.FileName);
            string newPathImg = Path.Combine(uploadDir, fileName);
            string imagePathNew = Server.MapPath(newPathImg);

            if (!string.IsNullOrEmpty(oldPathImg))
            {
                string pathOldImg = Path.Combine(Server.MapPath(uploadDir), Path.GetFileName(oldPathImg));

                if (System.IO.File.Exists(pathOldImg) && !pathOldImg.Equals(imagePathNew, StringComparison.OrdinalIgnoreCase))
                {
                    System.IO.File.Delete(pathOldImg);
                }
            }

            ImageFile.SaveAs(imagePathNew);

            return newPathImg;
        }

        public ActionResult Remove(int id)
        {
            var banerRemove = db.Banner.Where(x => x.ID == id).FirstOrDefault();
            if (banerRemove == null) return HttpNotFound();
            if (ModelState.IsValid)
            {
                banerRemove.IsDelete = true;
                db.Entry(banerRemove).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(banerRemove);
        }

        public ActionResult RestoreIndex()
        {
            var banner = db.Banner.Where(x => x.IsDelete).ToList();
            return View(banner);
        }
        public ActionResult Restore(int id)
        {
            var banner = db.Banner.Where(x => x.ID == id).FirstOrDefault();
            if (banner == null) return HttpNotFound();

            banner.IsDelete = false;
            db.Entry(banner).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("RestoreIndex");
        }
        [HttpGet]
        public ActionResult Search(string searchString)
        {
            if (string.IsNullOrEmpty(searchString)) return HttpNotFound();
            var banner = db.Banner
             .Where(x => x.Name.ToLower().Contains(searchString.ToLower()) && !x.IsDelete)
             .ToList();
            if (banner == null || banner.Count == 0) return HttpNotFound();
            return View(banner);
        }
    }
}

WEB_TRUONG_SP/Areas/Admin/Controllers/MenuController.cs
using PagedList;
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using WEB_TRUONG_SP.Models;

namespace WEB_TRUONG_SP.Areas.Admin.Controllers
{
    [RouteArea("Admin")]
    public class MenuController : Controller
    {
        ApplicationDBContext db = new ApplicationDBContext();
        public ActionResult Index(int? page )
        {
            int pageNumber = (page ?? 1);
            var menus = db.Menus.Where(x => !x.IsDelete).OrderByDescending(x=>x.CreateDate).ToList();
            int pageSize = 6;
            return View(menus.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(MenuModel menu)
        {
            if (ModelState.IsValid)
            {
                db.Menus.Add(menu);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(menu);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var menuEdit = db.Menus.Where(x => x.ID == id).FirstOrDefault();
            if (menuEdit == null) return HttpNotFound();
            return View(menuEdit);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MenuModel menu)
        {
            if (ModelState.IsValid)
            {
                menu.CreateDate = DateTime.Now;
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(menu);
        }

        public ActionResult Remove(int id)
        {
            var menuRemove = db.Menus.Where(x => x.ID == id).FirstOrDefault();
            if (menuRemove == null) return HttpNotFound();
            if (ModelState.IsValid)
            {
                menuRemove.IsDelete = true;
                db.Entry(menuRemove).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(menuRemove);
        }

        public ActionResult RestoreIndex()
        {
            var menus = db.Menus.Where(x => x.IsDelete).ToList();
            return View(menus);
        }
        public ActionResult Restore(int id)
        {
            var menu = db.Menus.Where(x => x.ID == id).FirstOrDefault();
            if (menu == null) return HttpNotFound();

            menu.IsDelete = false;
            db.Entry(menu).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("RestoreIndex");
        }
        [HttpGet]
        public ActionResult Search(string searchString)
        {
            if (string.IsNullOrEmpty(searchString)) return HttpNotFound();
            var menu = db.Menus
             .Where(x => x.Name.ToLower().Contains(searchString.ToLower()) && !x.IsDelete)
             .ToList();
            if (menu == null || menu.Count == 0) return HttpNotFound();
            return View(menu);
        }
    }
}

WEB_TRUONG_SP/Areas/Admin/Controllers/NewsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WEB_TRUONG_SP.Models;

namespace WEB_TRUONG_SP.Areas.Admin.Controllers
{
    [RouteArea("Admin")]
    public class NewsController : Controller
    {
        ApplicationDBContext db = new ApplicationDBContext();
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            var news = db.News.Where(x => !x.IsDelete).OrderByDescending(x => x.PublishDate).ToList();
            int pageSize = 6;
            return View(news.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult Add()
        {
            ViewBag.CategoryList = new SelectList(new List<SelectListItem>
    {
        new SelectListItem { Text = "Thông báo", Value = "Thông báo" },
        new SelectListItem { Text = "Hoạt động", Value = "Hoạt động" }
    }, "Value", "Text");

            var menus = db.Menus.Where(x => !x.IsDelete).Select(x => new
            {
                x.ID,
                x.Name
            }).ToList();

            ViewBag.MenuID = new SelectList(menus, "ID", "Name");

            var subMenus = db.SubMenu.Where(x => !x.IsDelete).Select(x => new
            {
                x.ID,
                x.Name
            }).ToList();

            ViewBag.subMenuID = new SelectList(subMenus, "ID", "Name");

            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Add(News news, HttpPostedFileBase ImageFile)
        {
            ModelState.Remove("IDMenu");
            ModelState.Remove("IDSubMenu");

            if (ModelState.IsValid)
            {
                var file = Request.Files["ImageFile"];
                if (file != null && file.ContentLength > 0)
                {
                    news.ImagePath = LoadImgName(ImageFile);
                    db.News.Add(news);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.CategoryList = new SelectList(new List<SelectListItem>
    {
        new SelectListItem { Text = "Thông báo", Value = "Thông báo" },
        new SelectListItem { Text = "Hoạt động", Value = "Hoạt động" }
    }, "Value", "Text", news.Category);

            var menus = db.Menus.Where(x => !x.IsDelete).Select(x => new
            {
                x.ID,
                x.Name
            }).ToList();

            ViewBag.MenuID = new SelectList(menus, "ID", "Name");

            var subMenus = db.SubMenu.Where(x => !x.IsDelete).Select(x => new
            {
                x.ID,
                x.Name
            }).ToList();

            ViewBag.subMenuID = new SelectList(subMenus, "ID", "Name");

            return View(news);
        }

        public string LoadImgName(HttpPostedFileBase ImageFile)
        {
            string path = "";
            if (ImageFile != null && ImageFile.ContentLength > 0)
            {
                var uploadDir = "~/ImgPath/ImgBG";
                var imagePath = Path.Combine(Server.MapPath(uploadDir), Path.GetFileName(ImageFile.FileName));
                path = Path.Combine(uploadDir, Path.GetFileName(ImageFile.FileName));
                ImageFile.SaveAs(imagePath);
            }
            return path;
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            ViewBag.CategoryList = new SelectList(new List<SelectListItem>
    {
        new SelectListItem { Text = "Thông báo", Value = "Thông báo" },
        new SelectListItem { Text = "Hoạt động", Value = "Hoạt động" }
    }, "Value", "Text");

            var menus = db.Menus.Where(x => !x.IsDelete).Select(x => new
            {
                x.ID,
                x.Name
            }).ToList();

            ViewBag.MenuID = new SelectList(menus, "ID", "Name");

            var subMenus = db.SubMenu.Where(x => !x.IsDelete).Select(x => new
            {
                x.ID,
                x.Name
            }).ToList();

            ViewBag.subMenuID = new SelectList(subMenus, "ID", "Name");

            var newEdit = db.News.Where(x => x.ID == id).FirstOrDefault();
            if (newEdit == null) return HttpNotFound();
            newEdit.PublishDate = DateTime.Parse(newEdit.PublishDate.ToString("yyyy-MM-dd"));
            return View(newEdit);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(News news, HttpPostedFileBase ImageFile)
        {
            ModelState.Remove("IDMenu");
            ModelState.Remove("IDSubMenu");
            if (ModelState.IsValid)
            {
                var oldPathImg = news.ImagePath;

                if (ImageFile != null && ImageFile.ContentLength > 0)
                {
                    news.ImagePath = CheckDeleteOrUpdateImg(oldPathImg, ImageFile);
                }
                else
                {
                    news.ImagePath = oldPathImg;
                }
                news.CreateDate = DateTime.Now;
                db.Entry(news).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryList = new SelectList(new List<SelectListItem>
    {
        new SelectListItem { Text = "Thông báo", Value = "Thông báo" },
        new SelectListItem { Text = "Hoạt động", Value = "Hoạt động" }
    }, "Value", "Text", news.Category);

            var menus = db.Menus.Where(x => !x.IsDelete).Select(x => new
            {
                x.ID,
                x.Name
            }).ToList();

            ViewBag.MenuID = new SelectList(menus, "ID", "Name");

            var subMenus = db.SubMenu.Where(x => !x.IsDelete).Select(x => new
            {
                x.ID,
                x.Name
            }).ToList();

            ViewBag.subMenuID = new SelectList(subMenus, "ID", "Name");

            return View(news);
        }

        public string CheckDeleteOrUpdateImg(string oldPathImg, HttpPostedFileBase ImageFile)
        {
            string uploadDir = "~/ImgPath/ImgBG";
            string fileName = Path.GetFileName(ImageFile.FileName);
            string newPathImg = Path.Combine(uploadDir, fileName);
            string imagePathNew = Server.MapPath(newPathImg);

            if (!string.IsNullOrEmpty(oldPathImg))
            {
                string pathOldImg = Path.Combine(Server.MapPath(uploadDir), Path.GetFileName(oldPathImg));

                if (System.IO.File.Exists(pathOldImg) && !pathOldImg.Equals(imagePathNew, StringComparison.OrdinalIgnoreCase))
                {
                    System.IO.File.Delete(pathOldImg);
                }
            }

            ImageFile.SaveAs(imagePathNew);

            return newPathImg;
        }

        public ActionResult Remove(int id)
        {
            var remove = db.News.Where(x => x.ID == id).FirstOrDefault();
            if (remove == null) return HttpNotFound();
            if (ModelState.IsValid)
            {
                remove.IsDelete = true;
                db.Entry(remove).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(remove);
        }

        public ActionResult RestoreIndex()
        {
            var news = db.News.Where(x => x.IsDelete).ToList();
            return View(news);
        }
        public ActionResult Restore(int id)
        {
            var news = db.News.Where(x => x.ID == id).FirstOrDefault();
            if (news == null) return HttpNotFound();

            news.IsDelete = false;
            db.Entry(news).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("RestoreIndex");
        }
        [HttpGet]
        public ActionResult Search(string searchString)
        {
            if (string.IsNullOrEmpty(searchString)) return HttpNotFound();
            var news = db.News
             .Where(x => x.Content.ToLower().Contains(searchString.ToLower()) && !x.IsDelete)
             .ToList();
            if (news == null || news.Count == 0) return HttpNotFound();
            return View(news);
        }
    }
}

WEB_TRUONG_SP/Areas/Admin/Views/Shared/AdminLayoutPage.cshtml
@using PagedList.Mvc;
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Areas/Contents/CSS/sb-admin-2.css" rel="stylesheet" />
    <link href="~/Areas/Contents/CSS/sb-admin-2.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/ckeditor5-42.0.1/ckeditor5/ckeditor5.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index", "Home")">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fa fa-home"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Admin</div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Home")">
                    <i class="fa fa-dashboard"></i>
                    <span>Thông báo</span>
                </a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Heading -->
            <div class="sidebar-heading">
                Quản lý Menu
            </div>
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index","Menu")" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fa fa-bookmark"></i>
                    <span>Menu chính</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index","SubMenu")" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fa fa-th-list"></i>
                    <span>Menu con</span>
                </a>
            </li>

            <!-- Heading -->
            <div class="sidebar-heading">
                Quản lý bản tin
            </div>
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index","News")" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fa fa-newspaper-o"></i>
                    <span>Tin tức</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index","Banner")" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fa fa-newspaper-o"></i>
                    <span>Banner</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index","Department")" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fa fa-fw fa-folder"></i>
                    <span>Đơn vị trực thuộc</span>
                </a>
            </li>

            <hr class="sidebar-divider">
            <!-- Heading -->
            <div class="sidebar-heading">
                Quản lý nhân viên
            </div>
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index","Lecturer")" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fa fa-fw fa-user-plus"></i>
                    <span>Ban giám hiệu & GV</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index", "Home", new {area=""})" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fa fa-fw fa-sign-out"></i>
                    <span>Đăng xuất</span>
                </a>
            </li>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                    <!-- /.container-fluid -->
                </div>
                <!-- End of Main Content -->
                <!-- Footer -->
                <footer class="sticky-footer bg-white">
                    <div class="container my-auto">
                        <div class="copyright text-center my-auto">
                            <span>Copyright &copy; Nguyễn Trường An 2024</span>
                        </div>
                    </div>
                </footer>
                <!-- End of Footer -->
            </div>
            <!-- End of Content Wrapper -->
        </div>
        <!-- End of Page Wrapper -->
        <!-- Custom scripts for all pages-->
        <script src="~/Scripts/jquery-3.7.1.js"></script>
        <script src="~/Content/ckeditor5-42.0.1/ckeditor5/ckeditor5.js"></script>
     
</body>
</html>